-- ==========================================
-- SCRIPT D'INSERTION DLP (Data Loss Prevention)
-- ==========================================

DELETE FROM anonymization_dict;

INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'ST2I', '***CODE_01***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'STUDI', '***CODE_02***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Société Tunisienne d''Informatique pour l''Ingénierie', '***CODE_03***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'TUNEPS', '***CODE_04***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'RACHAD', '***CODE_05***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'SESAME', '***CODE_06***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'ProjectIQ', '***CODE_07***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'HAICOP', '***CODE_08***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'ANME', '***CODE_09***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'INS', '***CODE_10***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'ONTT', '***CODE_11***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'STEG', '***CODE_12***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'CERT', '***CODE_13***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'BNA', '***CODE_14***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'STB', '***CODE_15***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'BTE', '***CODE_16***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'UBCI', '***CODE_17***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Bank of Africa', '***CODE_18***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Banque Centrale de Mauritanie', '***CODE_19***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Tunisie Télécom', '***CODE_20***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Orange Tunisie', '***CODE_21***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Total Tunisie', '***CODE_22***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Groupe Chimique Tunisien', '***CODE_23***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Expertise France', '***CODE_24***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'GIZ', '***CODE_25***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'AFD', '***CODE_26***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'BAD', '***CODE_27***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Banque Mondiale', '***CODE_28***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Autodesk', '***CODE_29***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Oracle', '***CODE_30***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Microsoft', '***CODE_31***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Jardins du Lac', '***CODE_32***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Avenue du Dollar', '***CODE_33***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Lac II', '***CODE_34***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'st2i.com.tn', '***CODE_35***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Karim Ben Salah', '***CODE_36***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Sonia Mejri', '***CODE_37***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Mehdi Trabelsi', '***CODE_38***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Ines Bouazizi', '***CODE_39***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Yassine Chaabane', '***CODE_40***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Amira Khelifi', '***CODE_41***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Ahmed Jlassi', '***CODE_42***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Fatma Gharbi', '***CODE_43***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Bilel Mrad', '***CODE_44***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Rim Sassi', '***CODE_45***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Hamza Oueslati', '***CODE_46***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Mariem Ferchichi', '***CODE_47***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Nabil Ayari', '***CODE_48***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Sarra Dridi', '***CODE_49***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Oussama Tlili', '***CODE_50***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Haifa Mansouri', '***CODE_51***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Wael Bouzid', '***CODE_52***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Asma Laabidi', '***CODE_53***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Moez Hammami', '***CODE_54***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Syrine Rejeb', '***CODE_55***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Rami Ben Ali', '***CODE_56***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Emna Kraiem', '***CODE_57***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Zied Ghariani', '***CODE_58***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Nour Slimani', '***CODE_59***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Sofiene Jebali', '***CODE_60***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Khouloud Ben Hmida', '***CODE_61***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Hichem Masmoudi', '***CODE_62***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Leila Ben Amor', '***CODE_63***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Anis Torjmen', '***CODE_64***', true, NOW(), NOW());
INSERT INTO anonymization_dict (id, original_word, replacement_code, is_active, created_at, updated_at) VALUES (gen_random_uuid(), 'Dorra Chouchene', '***CODE_65***', true, NOW(), NOW());
