-- ==========================================
-- SCRIPT D'INSERTION DLP (Data Loss Prevention)
-- ==========================================

DELETE FROM anonymization_dict;

INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('ST2I', '***CODE_01***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('STUDI', '***CODE_02***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Société Tunisienne d''Informatique pour l''Ingénierie', '***CODE_03***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('TUNEPS', '***CODE_04***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('RACHAD', '***CODE_05***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('SESAME', '***CODE_06***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('ProjectIQ', '***CODE_07***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('HAICOP', '***CODE_08***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('ANME', '***CODE_09***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('INS', '***CODE_10***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('ONTT', '***CODE_11***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('STEG', '***CODE_12***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('CERT', '***CODE_13***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('BNA', '***CODE_14***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('STB', '***CODE_15***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('BTE', '***CODE_16***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('UBCI', '***CODE_17***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Bank of Africa', '***CODE_18***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Banque Centrale de Mauritanie', '***CODE_19***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Tunisie Télécom', '***CODE_20***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Orange Tunisie', '***CODE_21***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Total Tunisie', '***CODE_22***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Groupe Chimique Tunisien', '***CODE_23***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Expertise France', '***CODE_24***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('GIZ', '***CODE_25***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('AFD', '***CODE_26***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('BAD', '***CODE_27***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Banque Mondiale', '***CODE_28***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Autodesk', '***CODE_29***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Oracle', '***CODE_30***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Microsoft', '***CODE_31***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Jardins du Lac', '***CODE_32***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Avenue du Dollar', '***CODE_33***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Lac II', '***CODE_34***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('st2i.com.tn', '***CODE_35***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Karim Ben Salah', '***CODE_36***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Sonia Mejri', '***CODE_37***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Mehdi Trabelsi', '***CODE_38***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Ines Bouazizi', '***CODE_39***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Yassine Chaabane', '***CODE_40***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Amira Khelifi', '***CODE_41***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Ahmed Jlassi', '***CODE_42***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Fatma Gharbi', '***CODE_43***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Bilel Mrad', '***CODE_44***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Rim Sassi', '***CODE_45***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Hamza Oueslati', '***CODE_46***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Mariem Ferchichi', '***CODE_47***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Nabil Ayari', '***CODE_48***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Sarra Dridi', '***CODE_49***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Oussama Tlili', '***CODE_50***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Haifa Mansouri', '***CODE_51***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Wael Bouzid', '***CODE_52***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Asma Laabidi', '***CODE_53***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Moez Hammami', '***CODE_54***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Syrine Rejeb', '***CODE_55***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Rami Ben Ali', '***CODE_56***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Emna Kraiem', '***CODE_57***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Zied Ghariani', '***CODE_58***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Nour Slimani', '***CODE_59***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Sofiene Jebali', '***CODE_60***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Khouloud Ben Hmida', '***CODE_61***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Hichem Masmoudi', '***CODE_62***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Leila Ben Amor', '***CODE_63***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Anis Torjmen', '***CODE_64***', true, NOW(), NOW());
INSERT INTO anonymization_dict (original_word, replacement_code, is_active, created_at, updated_at) VALUES ('Dorra Chouchene', '***CODE_65***', true, NOW(), NOW());
